### ISSUE TITLE
Change the [Region]

### ISSUE THREAD

**Issue by jrahma** [oracle/nosql-dotnet-sdk#2]
Hi,

Please name the Region here:

Region = Region.< your - region - here >,

to something else such as OracleRegion because it conflicts with Xamarin.Forms.Region

Thanks,
Jassim

**Comment by y-polonsk** [comment]
This is not feasible, because we need to keep naming consistency with other Oracle NoSQL language SDKs as well as OCI SDK (all languages) since all of them name it Region.  Please use aliases to handle naming conflicts.

Thanks.
